# Site settings
title: Data
permalink: pretty

# Build Settings
exclude:
  - package.json
  - README.md
  - CNAME
  - public/sass
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE

collections_dir: my_collections
collections:
  programmes:
    output: true
    permalink: /gc-journal/memos-2021-09-20/programmes/:name/

## ADD other settings below here
plugins:
  - jekyll-datapage-generator


#datapage-genrator config
page_gen-dirs: true

page_gen:
  - data: 'students-postings'
    template: 'student'
    name: 'gc'
    dir: 'students'