# Site settings
title: Data
permalink: pretty

# Build Settings
exclude:
  - package.json
  - README.md
  - CNAME
  - public/sass
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE

## ADD other settings below here
plugins:
  - jekyll-datapage-generator


#datapage-genrator config
page_gen-dirs: true

page_gen:
  - data: 'students-postings'
    template: 'student'
    name: 'stu-name'
    dir: 'students'